-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 21:36:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Amazon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Amazon` DEFAULT CHARACTER SET utf8 ;
USE `Amazon` ;

-- -----------------------------------------------------
-- Table `Amazon`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Author` (
  `Books_id` INT NOT NULL AUTO_INCREMENT,
  `First_col` VARCHAR(45) NULL,
  `Last_col` VARCHAR(45) NULL,
  `Adress` VARCHAR(45) NULL,
  PRIMARY KEY (`Books_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Books_has_Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Books_has_Author` (
  `Books_Books_id` INT NOT NULL AUTO_INCREMENT,
  `Author_Author_col` INT NULL,
  `Books_has_Author_col` VARCHAR(45) NULL,
  `Author_Books_id` INT NOT NULL,
  PRIMARY KEY (`Books_Books_id`, `Author_Books_id`),
  INDEX `fk_Books_has_Author_Author1_idx` (`Author_Books_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_has_Author_Author1`
    FOREIGN KEY (`Author_Books_id`)
    REFERENCES `Amazon`.`Author` (`Books_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Books` (
  `Reference_id` INT NOT NULL AUTO_INCREMENT,
  `Price_col` VARCHAR(45) NULL,
  `Author_col` INT NULL,
  `Availability_col` VARCHAR(45) NULL,
  `Books_has_Author_Books_Books_id` INT NOT NULL,
  PRIMARY KEY (`Reference_id`, `Books_has_Author_Books_Books_id`),
  INDEX `fk_Books_Books_has_Author1_idx` (`Books_has_Author_Books_Books_id` ASC) VISIBLE,
  CONSTRAINT `fk_Books_Books_has_Author1`
    FOREIGN KEY (`Books_has_Author_Books_Books_id`)
    REFERENCES `Amazon`.`Books_has_Author` (`Books_Books_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Catalogue_has_Books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Catalogue_has_Books` (
  `Catalogue_Catalogue_id` INT NOT NULL,
  `Books_Books` INT NULL,
  `Catalogue_has_Books_col` VARCHAR(45) NULL,
  `Books_Reference_id` INT NOT NULL,
  PRIMARY KEY (`Catalogue_Catalogue_id`, `Books_Reference_id`),
  INDEX `fk_Catalogue_has_Books_Books1_idx` (`Books_Reference_id` ASC) VISIBLE,
  CONSTRAINT `fk_Catalogue_has_Books_Books1`
    FOREIGN KEY (`Books_Reference_id`)
    REFERENCES `Amazon`.`Books` (`Reference_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Amazon`.`Catalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Amazon`.`Catalogue` (
  `Catalogue_id` INT NOT NULL AUTO_INCREMENT,
  `Book_col` VARCHAR(45) NULL,
  `Reference` VARCHAR(45) NULL,
  `Catalogue_has_Books_Catalogue_Catalogue_id` INT NOT NULL,
  PRIMARY KEY (`Catalogue_id`, `Catalogue_has_Books_Catalogue_Catalogue_id`),
  INDEX `fk_Catalogue_Catalogue_has_Books_idx` (`Catalogue_has_Books_Catalogue_Catalogue_id` ASC) VISIBLE,
  CONSTRAINT `fk_Catalogue_Catalogue_has_Books`
    FOREIGN KEY (`Catalogue_has_Books_Catalogue_Catalogue_id`)
    REFERENCES `Amazon`.`Catalogue_has_Books` (`Catalogue_Catalogue_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
