-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 21:45:37 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Networks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Networks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Networks` DEFAULT CHARACTER SET utf8 ;
USE `Networks` ;

-- -----------------------------------------------------
-- Table `Networks`.`Pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Networks`.`Pictures` (
  `Reference_id` INT NOT NULL AUTO_INCREMENT,
  `url_col` VARCHAR(45) NULL,
  `Adress_col` VARCHAR(45) NULL,
  `Users_col` VARCHAR(45) NULL,
  PRIMARY KEY (`Reference_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Networks`.`Users_has_Pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Networks`.`Users_has_Pictures` (
  `Users_Users_id` INT NOT NULL AUTO_INCREMENT,
  `Pictures_Pictures_col` INT NULL,
  `Users_has_Pictures_col` VARCHAR(45) NULL,
  `Pictures_Reference_id` INT NOT NULL,
  PRIMARY KEY (`Users_Users_id`, `Pictures_Reference_id`),
  INDEX `fk_Users_has_Pictures_Pictures1_idx` (`Pictures_Reference_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Pictures_Pictures1`
    FOREIGN KEY (`Pictures_Reference_id`)
    REFERENCES `Networks`.`Pictures` (`Reference_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Networks`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Networks`.`Users` (
  `Nickname_id` INT NOT NULL AUTO_INCREMENT,
  `First_col` VARCHAR(45) NULL,
  `Last_col` VARCHAR(45) NULL,
  `Email_col` VARCHAR(45) NULL,
  `Users_has_Pictures_Users_Users_id` INT NOT NULL,
  PRIMARY KEY (`Nickname_id`, `Users_has_Pictures_Users_Users_id`),
  INDEX `fk_Users_Users_has_Pictures1_idx` (`Users_has_Pictures_Users_Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Users_has_Pictures1`
    FOREIGN KEY (`Users_has_Pictures_Users_Users_id`)
    REFERENCES `Networks`.`Users_has_Pictures` (`Users_Users_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Networks`.`Networks_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Networks`.`Networks_has_Users` (
  `Networks_Networks_id` INT NOT NULL AUTO_INCREMENT,
  `Users_Users_col` INT NULL,
  `Networks_has_Users_col` VARCHAR(45) NULL,
  `Users_Nickname_id` INT NOT NULL,
  PRIMARY KEY (`Networks_Networks_id`, `Users_Nickname_id`),
  INDEX `fk_Networks_has_Users_Users1_idx` (`Users_Nickname_id` ASC) VISIBLE,
  CONSTRAINT `fk_Networks_has_Users_Users1`
    FOREIGN KEY (`Users_Nickname_id`)
    REFERENCES `Networks`.`Users` (`Nickname_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Networks`.`Networks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Networks`.`Networks` (
  `Users_id` INT NOT NULL AUTO_INCREMENT,
  `Friends_col` VARCHAR(45) NULL,
  `Networks_has_Users_Networks_Networks_id` INT NOT NULL,
  PRIMARY KEY (`Users_id`, `Networks_has_Users_Networks_Networks_id`),
  INDEX `fk_Networks_Networks_has_Users_idx` (`Networks_has_Users_Networks_Networks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Networks_Networks_has_Users`
    FOREIGN KEY (`Networks_has_Users_Networks_Networks_id`)
    REFERENCES `Networks`.`Networks_has_Users` (`Networks_Networks_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
