-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 21:07:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Shop` DEFAULT CHARACTER SET utf8mb4 ;
USE `Shop` ;

-- -----------------------------------------------------
-- Table `Shop`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Customer` (
  `Customer_id` INT NOT NULL,
  `Picture_col` INT NOT NULL,
  `First_col` VARCHAR(45) NULL,
  `Last_col` VARCHAR(45) NULL,
  `DNI_col` VARCHAR(45) NULL,
  PRIMARY KEY (`Picture_col`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Shop`.`Picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Shop`.`Picture` (
  `Picture_id` INT NOT NULL,
  `Price_col` VARCHAR(45) NULL,
  `Author_col` VARCHAR(45) NULL,
  `Customer_Customer_id` INT NOT NULL,
  PRIMARY KEY (`Picture_id`, `Customer_Customer_id`),
  INDEX `fk_Picture_Customer_idx` (`Customer_Customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Picture_Customer`
    FOREIGN KEY (`Customer_Customer_id`)
    REFERENCES `Shop`.`Customer` (`Customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
