-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 21:17:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Stube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Stube` DEFAULT CHARACTER SET utf8 ;
USE `Stube` ;

-- -----------------------------------------------------
-- Table `Stube`.`Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`Information` (
  `Information_id` INT NOT NULL AUTO_INCREMENT,
  `Password_col` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`Information_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stube`.`User_has_Information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`User_has_Information` (
  `User_User_id` INT NOT NULL AUTO_INCREMENT,
  `Information_Information` INT NOT NULL,
  `User_has_Information_col` VARCHAR(45) NULL,
  `Information_Information_id` INT NOT NULL,
  PRIMARY KEY (`User_User_id`, `Information_Information_id`, `Information_Information`),
  INDEX `fk_User_has_Information_Information1_idx` (`Information_Information_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Information_Information1`
    FOREIGN KEY (`Information_Information_id`)
    REFERENCES `Stube`.`Information` (`Information_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stube`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `Video` VARCHAR(45) NULL,
  `User_has_Information_User_User_id` INT NOT NULL,
  PRIMARY KEY (`User_id`, `User_has_Information_User_User_id`),
  INDEX `fk_User_User_has_Information_idx` (`User_has_Information_User_User_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_User_has_Information`
    FOREIGN KEY (`User_has_Information_User_User_id`)
    REFERENCES `Stube`.`User_has_Information` (`User_User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stube`.`User_has_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stube`.`User_has_Video` (
  `User_User_id` INT NOT NULL AUTO_INCREMENT,
  `Video_Video_id` INT NULL,
  `User_User_id2` INT NOT NULL,
  `User_User_has_Information_User_User_id1` INT NOT NULL,
  PRIMARY KEY (`User_User_id`, `User_User_id2`, `User_User_has_Information_User_User_id1`),
  INDEX `fk_User_has_Video_User2_idx` (`User_User_id2` ASC, `User_User_has_Information_User_User_id1` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Video_User2`
    FOREIGN KEY (`User_User_id2` , `User_User_has_Information_User_User_id1`)
    REFERENCES `Stube`.`User` (`User_id` , `User_has_Information_User_User_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
