-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 20:57:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seats` (
  `Seats_id` INT NOT NULL,
  `Planes_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Planes_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Planes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Planes` (
  `Planes_id` INT NOT NULL AUTO_INCREMENT,
  `Capacitat_col` INT NULL,
  `Model_col` VARCHAR(45) NULL,
  `Seats_id` INT NOT NULL,
  PRIMARY KEY (`Planes_id`, `Seats_id`),
  INDEX `fk_Planes_Seats_idx` (`Seats_id` ASC) VISIBLE,
  CONSTRAINT `fk_Planes_Seats`
    FOREIGN KEY (`Seats_id`)
    REFERENCES `mydb`.`Seats` (`Seats_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
